// This file is auto-generated by scripts/generate-config.js. Do not edit or commit.
export const CONFIG = {
    FIREBASE: {
        "projectId": "election-262a7",
        "appId": "1:449298582484:web:937e605224f469a2eaa441",
        "storageBucket": "election-262a7.firebasestorage.app",
        "apiKey": "AIzaSyAT7FH1J8qLdlC51d4DwPuJg2j3qSRBr2w",
        "authDomain": "election-262a7.firebaseapp.com",
        "messagingSenderId": "449298582484",
        "measurementId": "G-ZDPFP4DYHZ"
    },
    AI_PROVIDER: "gemini",
    GEMINI_API_KEY: "AIzaSyC7EapNkLDFZWO9z9rYRYqa74ayRwaye30",
    GEMINI_MODEL: "gemini-2.0-flash",
    TRANSLATE_API_KEY: "AIzaSyC7EapNkLDFZWO9z9rYRYqa74ayRwaye30"
};
