// Generates config.js at the repo root from environment variables.
// config.js is gitignored; this script runs before `vite build` and `vite`.
import { writeFileSync, existsSync, readFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const rootDir = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const outPath = resolve(rootDir, 'config.js');
const envPath = resolve(rootDir, '.env');

// Parse .env if present
if (existsSync(envPath)) {
    const envLines = readFileSync(envPath, 'utf8').split(/\r?\n/);
    for (const line of envLines) {
        const trimmed = line.trim();
        if (!trimmed || trimmed.startsWith('#')) continue;
        const eqIdx = trimmed.indexOf('=');
        if (eqIdx !== -1) {
            const key = trimmed.slice(0, eqIdx).trim();
            const val = trimmed.slice(eqIdx + 1).trim().replace(/^['"]|['"]$/g, '');
            if (!process.env[key]) {
                process.env[key] = val;
            }
        }
    }
}

const DEFAULT_FIREBASE_CONFIG = {
    projectId: "election-262a7",
    appId: "1:449298582484:web:937e605224f469a2eaa441",
    storageBucket: "election-262a7.firebasestorage.app",
    apiKey: "AIzaSyAT7FH1J8qLdlC51d4DwPuJg2j3qSRBr2w",
    authDomain: "election-262a7.firebaseapp.com",
    messagingSenderId: "449298582484",
    measurementId: "G-ZDPFP4DYHZ"
};

const rawFirebase = process.env.FIREBASE_CONFIG;
let firebaseConfig = DEFAULT_FIREBASE_CONFIG;

if (rawFirebase && rawFirebase.trim()) {
    try {
        firebaseConfig = JSON.parse(rawFirebase);
    } catch (err) {
        console.error(`[generate-config] FIREBASE_CONFIG is not valid JSON: ${err.message}`);
        process.exit(1);
    }

    if (firebaseConfig === null || typeof firebaseConfig !== 'object' || Array.isArray(firebaseConfig)) {
        console.error('[generate-config] FIREBASE_CONFIG must be a JSON object.');
        process.exit(1);
    }
}

const aiProvider = process.env.AI_PROVIDER || 'gemini';
const geminiApiKey = process.env.GEMINI_API_KEY || 'AIzaSyC7EapNkLDFZWO9z9rYRYqa74ayRwaye30';
const geminiModel = process.env.GEMINI_MODEL || 'gemini-2.0-flash';
const translateApiKey = process.env.TRANSLATE_API_KEY || 'AIzaSyC7EapNkLDFZWO9z9rYRYqa74ayRwaye30';

const output = `// This file is auto-generated by scripts/generate-config.js. Do not edit or commit.
export const CONFIG = {
    FIREBASE: ${JSON.stringify(firebaseConfig, null, 4).replace(/\n/g, '\n    ')},
    AI_PROVIDER: ${JSON.stringify(aiProvider)},
    GEMINI_API_KEY: ${JSON.stringify(geminiApiKey)},
    GEMINI_MODEL: ${JSON.stringify(geminiModel)},
    TRANSLATE_API_KEY: ${JSON.stringify(translateApiKey)}
};
`;

writeFileSync(outPath, output, 'utf8');
console.log('[generate-config] Wrote config.js');
